#指定端口号
server:
  port: 8761
#指定服务名称
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false    # 是否注册到eureka
    fetch-registry: false          # 是否从eureka获取信息
    service-url:
      #eureka地址信息
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka